experiment_name: "Skin Cancer Detection"
tracking_uri: "http://localhost:5000"
batch_size: 128
learning_rate: 0.0001
num_epochs: 3
patience: 3
train_csv_path: "data/processed/train.csv"
train_hdf5_path: "data/raw/isic-2024-challenge/train-image.hdf5"
model_path: "Models/hybrid_model.pth"
checkpoint_path: "Models/checkpoints"